import { Property } from './property';

export const DEFAULT_DATA: Property[] = [
  {
    id: 1,
    imageUrl: '',
    imageAlt: 'Rear view of modern home with pool',
    commercialType: 'Para Venda',
    title: 'Casa de Praia em Guarujá',
    address: 'Rua 1',
    number: 1,
    city: 'São Paulo',
    state: 'SP',
    zipCode: '00000-000',
    bedrooms: 1,
    bathrooms: 1,
    squareFoot: 1,
    price: 1000,
    garage: 1,
    description: 'Descrição 1',
    dateAdded: new Date(),
    rentValue: {
      rent: 'R$ 1,00',
      securityDeposit: 'R$ 1,00',
      leaseDuration: '12 meses',
    },
    amenities: [
      { name: 'Ar Condicionado', value: true },
      { name: 'Sótão', value: true },
      { name: 'Piscina', value: true },
      { name: 'Churrasqueira', value: true },
    ],

    images: [
      {
        url: '',
        alt: 'Rear view of modern home with pool',
      },
    ],
  },
  {
    id: 2,
    imageUrl: '',
    imageAlt: 'Rear view of modern home with pool',
    commercialType: 'Para Venda',
    title: 'Casa de Praia em Guarujá',
    address: 'Rua 1',
    number: 1,
    city: 'São Paulo',
    state: 'SP',
    zipCode: '00000-000',
    bedrooms: 1,
    bathrooms: 1,
    squareFoot: 1,
    price: 1000,
    garage: 1,
    description: 'Descrição 1',
    dateAdded: new Date(),
    rentValue: {
      rent: 'R$ 1,00',
      securityDeposit: 'R$ 1,00',
      leaseDuration: '12 meses',
    },
    amenities: [
      { name: 'Ar Condicionado', value: true },
      { name: 'Sótão', value: true },
      { name: 'Piscina', value: true },
      { name: 'Churrasqueira', value: true },
    ],

    images: [
      {
        url: '',
        alt: 'Rear view of modern home with pool',
      },
    ],
  },
  {
    id: 3,
    imageUrl: '',
    imageAlt: 'Rear view of modern home with pool',
    commercialType: 'Para Venda',
    title: 'Casa de Praia em Guarujá',
    address: 'Rua 1',
    number: 1,
    city: 'São Paulo',
    state: 'SP',
    zipCode: '00000-000',
    bedrooms: 1,
    bathrooms: 1,
    squareFoot: 1,
    price: 1000,
    garage: 1,
    description: 'Descrição 1',
    dateAdded: new Date('2020-01-01 00:00:00'),
    rentValue: {
      rent: 'R$ 1,00',
      securityDeposit: 'R$ 1,00',
      leaseDuration: '12 meses',
    },
    amenities: [
      { name: 'Ar Condicionado', value: true },
      { name: 'Sótão', value: true },
      { name: 'Piscina', value: true },
      { name: 'Churrasqueira', value: true },
    ],

    images: [
      {
        url: '',
        alt: 'Rear view of modern home with pool',
      },
    ],
  },
  {
    id: 4,
    imageUrl: '',
    imageAlt: 'Rear view of modern home with pool',
    commercialType: 'Para Venda',
    title: 'Casa de Praia em Guarujá',
    address: 'Rua 1',
    number: 1,
    city: 'São Paulo',
    state: 'SP',
    zipCode: '00000-000',
    bedrooms: 1,
    bathrooms: 1,
    squareFoot: 1,
    price: 1000,
    garage: 1,
    description: 'Descrição 1',
    dateAdded: new Date(),
    rentValue: {
      rent: 'R$ 1,00',
      securityDeposit: 'R$ 1,00',
      leaseDuration: '12 meses',
    },
    amenities: [
      { name: 'Ar Condicionado', value: true },
      { name: 'Sótão', value: true },
      { name: 'Piscina', value: true },
      { name: 'Churrasqueira', value: true },
    ],

    images: [
      {
        url: '',
        alt: 'Rear view of modern home with pool',
      },
    ],
  },
  {
    id: 5,
    imageUrl: '',
    imageAlt: 'Rear view of modern home with pool',
    commercialType: 'Para Venda',
    title: 'Casa de Praia em Guarujá',
    address: 'Rua 1',
    number: 1,
    city: 'São Paulo',
    state: 'SP',
    zipCode: '00000-000',
    bedrooms: 1,
    bathrooms: 1,
    squareFoot: 1,
    price: 1000,
    garage: 1,
    description: 'Descrição 1',
    dateAdded: new Date(),
    rentValue: {
      rent: 'R$ 1,00',
      securityDeposit: 'R$ 1,00',
      leaseDuration: '12 meses',
    },
    amenities: [
      { name: 'Ar Condicionado', value: true },
      { name: 'Sótão', value: true },
      { name: 'Piscina', value: true },
      { name: 'Churrasqueira', value: true },
    ],

    images: [
      {
        url: '',
        alt: 'Rear view of modern home with pool',
      },
    ],
  },
  {
    id: 6,
    imageUrl: '',
    imageAlt: 'Rear view of modern home with pool',
    commercialType: 'Para Venda',
    title: 'Casa de Praia em Guarujá',
    address: 'Rua 1',
    number: 1,
    city: 'São Paulo',
    state: 'SP',
    zipCode: '00000-000',
    bedrooms: 1,
    bathrooms: 1,
    squareFoot: 1,
    price: 1000,
    garage: 1,
    description: 'Descrição 1',
    dateAdded: new Date(),
    rentValue: {
      rent: 'R$ 1,00',
      securityDeposit: 'R$ 1,00',
      leaseDuration: '12 meses',
    },
    amenities: [
      { name: 'Ar Condicionado', value: true },
      { name: 'Sótão', value: true },
      { name: 'Piscina', value: true },
      { name: 'Churrasqueira', value: true },
    ],

    images: [
      {
        url: '',
        alt: 'Rear view of modern home with pool',
      },
    ],
  },
  {
    id: 7,
    imageUrl: '',
    imageAlt: 'Rear view of modern home with pool',
    commercialType: 'Para Venda',
    title: 'Casa de Praia em Guarujá',
    address: 'Rua 1',
    number: 1,
    city: 'São Paulo',
    state: 'SP',
    zipCode: '00000-000',
    bedrooms: 1,
    bathrooms: 1,
    squareFoot: 1,
    price: 1000,
    garage: 1,
    description: 'Descrição 1',
    dateAdded: new Date('2020-01-01 00:00:00'),
    rentValue: {
      rent: 'R$ 1,00',
      securityDeposit: 'R$ 1,00',
      leaseDuration: '12 meses',
    },
    amenities: [
      { name: 'Ar Condicionado', value: true },
      { name: 'Sótão', value: true },
      { name: 'Piscina', value: true },
      { name: 'Churrasqueira', value: true },
    ],
    images: [
      {
        url: '',
        alt: 'Rear view of modern home with pool',
      },
    ],
  },
  {
    id: 8,
    imageUrl: '',
    imageAlt: 'Rear view of modern home with pool',
    commercialType: 'Para Venda',
    title: 'Casa de Praia em Guarujá',
    address: 'Rua 1',
    number: 1,
    city: 'São Paulo',
    state: 'SP',
    zipCode: '00000-000',
    bedrooms: 1,
    bathrooms: 1,
    squareFoot: 1,
    price: 1000,
    garage: 1,
    description: 'Descrição 1',
    dateAdded: new Date(),
    rentValue: {
      rent: 'R$ 1,00',
      securityDeposit: 'R$ 1,00',
      leaseDuration: '12 meses',
    },
    amenities: [
      { name: 'Ar Condicionado', value: true },
      { name: 'Sótão', value: true },
      { name: 'Piscina', value: true },
      { name: 'Churrasqueira', value: true },
    ],
    images: [
      {
        url: '',
        alt: 'Rear view of modern home with pool',
      },
    ],
  },
];
